-- V14:



ALTER TABLE daily_ledger

    MODIFY COLUMN source ENUM('COLLECTION','PURCHASE','INVESTMENT','WITHDRAWAL','PROFIT_DISTRIBUTION','OPERATING_EXPENSE','MANUAL') NOT NULL,

    MODIFY COLUMN reference_type ENUM('PAYMENT','PURCHASE','INVESTMENT','WITHDRAWAL','PROFIT_DISTRIBUTION', 'CONTRACT_EXPENSE', 'MANUAL') NOT NULL;
